### ISSUE TITLE
How can I import a hot box that I've already created?

### ISSUE THREAD

**Issue by effiraid** [luckylyk/hotbox_designer#1]
Isn't not support yet?

**Comment by luckylyk** [comment]
Hi,
In the manager window, there's a button "import"  (under the hotboxes list)
I implemented it 2 days ago, so if you don't have the button, install the latest script's version :)

Thx to following the tool
good luck
Lionel

**Comment by effiraid** [comment]
Thanks! I tried to use it as a picker. The result was very useful.
![kakaotalk_20181112_031239809](https://user-images.githubusercontent.com/29611806/48552363-b8494b00-e91b-11e8-9ce0-22a58344b4d9.png)

**Comment by luckylyk** [comment]
:) aah, super nice ! Thanks for the share.
I should add some templates like this directly in the tool :)
