### ISSUE TITLE
Hover running script twice

### ISSUE THREAD

**Issue by navem** [luckylyk/hotbox_designer#11]
Hi 

I have a scene with a bunch of shots in maya sequencer and have this script assigned to a button to jump to next shot:

```
sequencerGotoShot 1;
$currentShotUpdate = `sequenceManager -q -cs`;
playbackOptions -minTime `shot -q -st $currentShotUpdate`;
playbackOptions -animationStartTime `shot -q -st $currentShotUpdate`;
playbackOptions -maxTime `shot -q -et $currentShotUpdate`;
playbackOptions -animationEndTime `shot -q -et $currentShotUpdate`;
currentTime `shot -q -st $currentShotUpdate`;
```

When I use click on the button, the script is run once, as expected. But when I use the gesture, it runs the script twice? It seems to be based on time delay. If I gesture VERY quickly, it's executed 1 time. If I gesture slowly, it's run twice.

**Comment by luckylyk** [comment]
This should be fixed by the latest commit.
Don't forget to send me your Hotbox screenshot ! I want to see that.

**Comment by navem** [comment]
Thanks Lio! I will test it out on Monday. How can I send screenshot privately?

**Comment by luckylyk** [comment]
There is no pm on Github. But lionel.brouyere@gmail.com is fine 😁
