### ISSUE TITLE
Can you support for maya 2016?

### ISSUE THREAD

**Issue by effiraid** [luckylyk/hotbox_designer#4]
from hotbox_designer.manager import HotboxManager
from hotbox_designer.softwares import Maya
hotboxes_manager = HotboxManager(Maya())
hotboxes_manager.show()
# Error: ImportError: file C:/Users/NOTEBOOK/Documents/maya/2016/scripts\hotbox_designer\reader.py line 1: No module named PySide2 # 

Here's the error.

**Comment by luckylyk** [comment]
outcha :) convert everything for PySide 1 is a big deal. I prefere concentrate my time on the bugs fixe and new features .. sorry.
You can try to rename all: 
PySide2 --> PySide

**Comment by luckylyk** [comment]
and all QtWidgets --> QtGui

**Comment by luckylyk** [comment]
ok I discussed with a friend, I already changed my mind cause it can help for Natron integration.. i will try something, but it's a big feature it's not for tomorrow :)

**Comment by effiraid** [comment]
Thanks!

**Comment by luckylyk** [comment]
Hi ignasiduelo,
Thanks for the share.

I don't want to create non-standard dependence for hotbox designer. I wan't to keep it cleaner as possible. But as its a not a big deal, I created a special branch using Qt for maya version older than 2017.
https://github.com/luckylyk/hotbox_designer/tree/maya-2016. (this branch will not follow the updates).
I don't have maya 2016 to test, but it works on 2017 and I think it ok.
Tell me.
I didn't add the Qt module inside the branch so you have to add it in the maya script folder root :).

I hope it can help, 
let me know.
